### ISSUE TITLE
Invalid id in ncx

### ISSUE THREAD

**Issue by toshiya44** [dteviot/WebToEpub#17]
IDs must start with a letter but in the toc only 4 digit numbers are used.
Please replace them with something like `toc_[4digitnumberhere]` for maximum compatibility.

**Comment by belldandu** [comment]
@toshiya44 Epubcheck agrees the id's are invalid however there are also some other errors that i do need to address such as the cite_refs being invalid uri's because they are not properly relative paths (the amount of times that shows up is almost ridiculous)

@dteviot i will make a push later today to fix all the errors from epubcheck including this one. As i would rather not have these errors become problems down the road.

This specific issue however will be solves by appending before everything "Body" and not toc_.

**Comment by belldandu** [comment]
@dteviot @toshiya44 fixed in #19

**Comment by toshiya44** [comment]
Should I close this? @belldandu

**Comment by dteviot** [comment]
Not until you've verified the release in your possession fixes the issue.

**Comment by belldandu** [comment]
@dteviot This issue was of the id being invalid because it had a number first and not a letter which was fixed here https://github.com/dteviot/WebToEpub/blob/0bebd35d879038eb521799ada6f128999e71c4b0/plugin/js/EpubPacker.js#L231

Here is the function https://github.com/dteviot/WebToEpub/blob/0bebd35d879038eb521799ada6f128999e71c4b0/plugin/js/EpubPacker.js#L259

The function appends to the beginning of the id ```body``` which does solve this specific issue of id's in the toc being invalid.

@toshiya44 if 0.0.0.7 (which it should) no longer has invalid id's (which it shouldn't because i went on a fixing spree to get rid of all the epubcheck errors) then yes you may close this.

**Comment by dteviot** [comment]
@belldandu,  I was not intending to slight you, or imply that it was not fixed.
It's just my policy is that people should not close an incident until they've seen for themselves that it's been fixed, and not just take my (or anyone else's word for it.)  Mistakes happen, and bug fixes sometimes don't work on the end users PC.  And I apologise I'm telling you nothing you don't already know.

**Comment by belldandu** [comment]
@dteviot thats fine.

**Comment by dteviot** [comment]
@belldandu and I forgot to say thank you for doing all that work

**Comment by belldandu** [comment]
@dteviot XD its no problem at all. Your Welcome :P

**Comment by belldandu** [comment]
@toshiya44 Have you had a chance to check this out?

**Comment by toshiya44** [comment]
@belldandu Yes, IDs has been fixed.
