### ISSUE TITLE
Add marx2mao.com

### ISSUE THREAD

**Issue by poopingpenis** [dteviot/WebToEpub#448]
This site has a lot of good books and texts that are not available on epub anywhere. Would love to see it added. :)
http://www.marx2mao.com

**Comment by poopingpenis** [comment]
A note on the texts of this site, they will usually be separated into new lines where a new page starts, with some small text on the left or right indicating page number.

**Comment by dteviot** [comment]
Notes for self:
This seems to be a Table of Contents page:  http://www.marx2mao.com/RG.html

**Comment by dteviot** [comment]
@poopingpenis 
> A note on the texts of this site, they will usually be separated into new lines where a new page starts, with some small text on the left or right indicating page number.

I assume you mean something like http://www.marx2mao.com/M&E/SUS80.html.  Which is a single html document, that contains text from multiple pages of the original.
WebToEpub would treat this as a single chapter

**Comment by poopingpenis** [comment]
@dteviot 

> I assume you mean something like http://www.marx2mao.com/M&E/SUS80.html. Which is a single html document, that contains text from multiple pages of the original.
> WebToEpub would treat this as a single chapter

Yes, I meant that.

**Comment by dteviot** [comment]
@poopingpenis
I've implemented a parser for http://www.marx2mao.com/, 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

However this site is really no different to marxists.org, so the supplied parser really isn't any different to the default parser.

To explain 
The way WebToEpub works is:
1. You give it a list of URLs
2. It fetches the HTML page associated with the URL
3. Selects the element on the page with the wanted content, and any associated iamges and generates a new HTML page.
4. Packs the HTML pages in sequence into an Epub.
5. Using the URLs to create a Table to Contents for the Epub

Also, WebToEpub has some logic that goes Starting with a given page, assume it's a Table of Contents page, so here's how to generate the list of URLs of pages to fetch

For marx2mao, 
1. The List of URLs is basically the URLS on the page, and
2. For each "chapter" page, the wanted element is the whole page.  (The &lt;body&gt; element)
3. Some "chapter" pages, are Table of Content pages themselves.  However, WebToEpub doesn't handle trying to recursively fetch that content.

This is the same as what the basic parser does.
The only difference is, it won't ask you for the settings.

(note, I'm going to be busy with other things for the next few days, so don't expect any prompt responses.)

**Comment by poopingpenis** [comment]
It still doesn't seem to properly pick up the chapters in a document, and fills up with irrelevant ones.

For example, try running the add-on on this page http://www.marx2mao.com/Mao/OC37.html

(I'm using Firefox.)

**Comment by dteviot** [comment]
@poopingpenis
> It still doesn't seem to properly pick up the chapters in a document,

I assume you're referring to the fact that for that URL it's only selecting the "On Contradiction" and not the links for "The Two World Outlooks", "The Universality of Contradiction" etc.
The reason for this is, all the chapter links are to the same HTML page. e.g.
ON CONTRADICTION's URL is http://www.marx2mao.com/Mao/OC37.html#C
The Two World Outlooks ULR is http://www.marx2mao.com/Mao/OC37.html#C1

They only differ by the bit after the #, which indicates a position on the HTML page.
As the URLs are to the same page, WebToEpub only keeps the first one it finds, as there is no reason to fetch multple copies of the same page.

**Comment by dteviot** [comment]
Updated version 0.0.0.125 has been uploaded to Firefox and Chrome stores. Firefox version is available, Chrome should be available in 3 to 7 days, once it finishes review.
